### ISSUE TITLE
No way to check if a block is connected to the core.

### ISSUE THREAD

**Issue by Matecik** [Matecik/MaF-SVGC2018#1]
Some static method should be made that checks if a given block is connected to the core.

**Comment by ghost** [comment]
@max

**Comment by Matecik** [comment]
Good job @CounterproductiveMarshmallow, I am pretty sure you just atted a random person.

**Comment by Matecik** [comment]
Looking them up it looks like they are GitHub staff.

**Comment by Matecik** [comment]
10/10.

**Comment by Matecik** [comment]
This is fixed now.
